version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'develop'
    schedule:
      interval: 'daily'
    assignees:
      - 'austintoddj'
    labels:
      - 'npm'
      - 'dependencies'
